# log every proxy request
LogRequests=true

# bind address to use. If enabling TLS, bind address must be :80 to allow for letsencrypt to work
BindAddress = ":8080"

# should we use TLS, and TLS bind address. This will auto-cert the domains when needed
TlsEnabled = false
TlsBindAddress = ":4433"

# domain forward to TLS (https) target, accepting invalid cert on target
[[rule]]
job="proxy"
domain="example.com"
target="https://internal.example.com"
acceptSelfSigned=true

# forward regex match as well :) *.example.org/... will forward to internal.example.org/wwwsite/...
# regex matches example.org itself too. To grab only +.example.org, but not example.org itself: '^(.+\.)example.org'
# first character in domain '^' denounces regex search
[[rule]]
job="proxy"
domain='^(.+\.|)example.org'
target="http://internal.example.org/wwwsite"

# redirecting a domain to another one
# https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#3xx_Redirection
[[rule]]
job="redirect"
domain="www.example.com"
target="https://www.google.co.uk"
statusCode=301

# using regex to create default action and override the default Forbidden 403
# you can also use regex=true instead of the starting regex ^
[[rule]]
job="redirect"
domain='.*'
regex=true
target="https://www.google.co.uk"
statusCode=307
